# Generated by Django 5.2 on 2025-06-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL to fetch from the web.', null=True),
        ),
    ]
