# Generated by Django 5.2 on 2025-06-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL to use a web image for this category.', null=True),
        ),
    ]
