# Generated by Django 5.2 on 2025-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark this as the primary category image.'),
        ),
    ]
