"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'marketplace',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'marketplace', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marketplace.context_processors.footer_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = 'marketplace:login'
LOGIN_REDIRECT_URL = 'marketplace:home'
LOGOUT_REDIRECT_URL = 'marketplace:home'

# Messages settings
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jonaldsabordo@gmail.com'  # <-- Replace with your Gmail address
EMAIL_HOST_PASSWORD = 'eeonixvlxxusszam'       # <-- Replace with your Gmail App Password
DEFAULT_FROM_EMAIL = 'Local Marketplace <jonaldsabordo@gmail.com>'
ADMIN_EMAIL = 'jonaldsabordo@gmail.com'      # <-- Replace with your Gmail address

# SimpleUI Settings
SIMPLEUI_HOME_PAGE = '/admin/home/'  # Updated with trailing slash
SIMPLEUI_HOME_TITLE = 'Marketplace Analytics Dashboard'
SIMPLEUI_HOME_ICON = 'fa fa-gauge'
SIMPLEUI_ANALYSIS = True

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['Marketplace', 'Authentication and Authorization'],
    'dynamic': True,
    'menus': [
        {
            'name': 'Marketplace',
            'icon': 'fas fa-store',
            'models': [
                {
                    'name': 'Products',
                    'icon': 'fas fa-box',
                    'url': 'marketplace/product/'
                },
                {
                    'name': 'Orders',
                    'icon': 'fas fa-shopping-cart',
                    'url': 'marketplace/order/'
                },
                {
                    'name': 'Categories',
                    'icon': 'fas fa-tags',
                    'url': 'marketplace/category/'
                },
            ]
        },
    ]
}

SIMPLEUI_HOME_INFO = [
    {
        'title': 'Marketplace Overview',
        'icon': 'fas fa-chart-line',
        'content': [
            {
                'type': 'row',
                'gutter': 16,
                'children': [
                    {
                        'type': 'card',
                        'title': 'Total Sales',
                        'icon': 'fas fa-money-bill',
                        'content': '<h2 id="total-sales">₱0</h2><div>Revenue</div>',
                        'span': 6,
                        'chart': {
                            'type': 'line',
                            'data': []
                        }
                    },
                    {
                        'type': 'card',
                        'title': 'Orders',
                        'icon': 'fas fa-shopping-cart',
                        'content': '<h2 id="orders-count">0</h2><div>Total Orders</div>',
                        'span': 6,
                        'chart': {
                            'type': 'bar',
                            'data': []
                        }
                    },
                    {
                        'type': 'card',
                        'title': 'Products',
                        'icon': 'fas fa-box',
                        'content': '<h2 id="products-count">0</h2><div>Active Products</div>',
                        'span': 6
                    },
                    {
                        'type': 'card',
                        'title': 'Users',
                        'icon': 'fas fa-users',
                        'content': '<h2 id="users-count">0</h2><div>Registered Users</div>',
                        'span': 6
                    }
                ]
            },
            {
                'type': 'chart',
                'title': 'Sales Trends',
                'span': 24,
                'option': {
                    'title': {'text': 'Monthly Sales'},
                    'tooltip': {'trigger': 'axis'},
                    'legend': {'data': ['Revenue', 'Orders']},
                    'xAxis': {'type': 'category', 'data': []},
                    'yAxis': [
                        {'type': 'value', 'name': 'Revenue (₱)'},
                        {'type': 'value', 'name': 'Orders'}
                    ],
                    'series': [
                        {
                            'name': 'Revenue',
                            'type': 'line',
                            'data': []
                        },
                        {
                            'name': 'Orders',
                            'type': 'bar',
                            'data': []
                        }
                    ]
                }
            },
            {
                'type': 'chart',
                'title': 'Regional Distribution',
                'span': 12,
                'option': {
                    'title': {'text': 'Sales by Region'},
                    'tooltip': {'trigger': 'item'},
                    'legend': {'orient': 'vertical', 'left': 'left'},
                    'series': [
                        {
                            'name': 'Sales Distribution',
                            'type': 'pie',
                            'radius': '50%',
                            'data': []
                        }
                    ]
                }
            },
            {
                'type': 'chart',
                'title': 'Top Categories',
                'span': 12,
                'option': {
                    'title': {'text': 'Sales by Category'},
                    'tooltip': {'trigger': 'axis'},
                    'xAxis': {'type': 'category', 'data': []},
                    'yAxis': {'type': 'value'},
                    'series': [
                        {
                            'name': 'Sales',
                            'type': 'bar',
                            'data': []
                        }
                    ]
                }
            }
        ]
    }
]

# SimpleUI Settings
SIMPLEUI_STATIC_OFFLINE = True  # Use local static files
SIMPLEUI_CUSTOM_CSS = 'css/admin-fixes.css'  # Path to our custom CSS fixes
